---
title: "Применение средств и методов OSINT"
author: "Артём Ванифатов"
format: 
    md:
        output-file: README.md
engine: knitr
---

## Цель работы

1. Освоить базовые подходы процессов OSINT

2. Освоить современные инструменты поиска и сбора информации

3. Освоить инструменты совместной работы в ходе аналитической деятельности

## Задание

1. Собрать информацию о компании Innostage

2. Собрать информацию об основных специализированных технологиях, применяемых в средствах защиты информации

3. Собрать информацию о публичных сотрудниках, ведущих профильные технологические блоги, профили в социальных сетях и т.д.

4. Сформировать представление о рынке отечественных решений ИБ

## Ход работы

### 1. Основная информация о компании

Полное название компании - Общество с ограниченной ответственностью "ИННОСТЕЙДЖ"

ИНН - 1655428600

ОГРН - 1191690099028

КПП - 165501001

ОКПО - 42514871

Юридический адрес - 420015, Республика Татарстан, г. Казань, ул. Подлужная, д. 60, офис 101

[Источник](https://checko.ru/company/innosteydzh-1191690099028) 

### 2. Структура компании

Гузаиров Айдар Фаилевич - генеральный директор

Каюмов Наиль Абдулхаевич - заместитель генерального директора

Дроздиков Дмитрий Валерьевич - директор по производству

Погосян Армине Араевна - HR-директор

[Источник](https://innostage-group.ru/company/staff/rukovoditeli/)

### 3. Основные направления деятельности компании

#### Услуги:

Кибербезопасность:

- Мониторинг событий информационной безопасности
- Анализ и контроль защищённости
- Обеспечение безопасности данных предприятия
- Обеспечение сетевой безопасности

Безопасность промышленных систем:

- Аудит информационной безопасности систем промышленной автоматизации
- Создание систем обеспечения информационной безопасности АСУ ТП
- Внедрение специализированных средств защиты информации АСУ ТП
- Разработка методического обеспечения ИБ АСУ ТП

ИТ-инфраструктура:

- Виртуализация ИТ-инфраструктуры
- Технологии обеспечения высокой доступности ИТ
- Базовые инфраструктурные сервисы
- Управление ИТ-инфраструктурой
- Облачные решения
- Решения OpenSource и импортозамещение ИТ-инфраструктуры
- Серверы и СХД

Построение и модернизация ЦОД:

- Информационная инфраструктура
- Инженерная инфраструктура
- Информационная безопасность ЦОД

Инженерные системы зданий:

- Создание систем обеспечения физической безопасности
- Создание систем обеспечения пожарной безопасности
- Создание информационных систем
- Создание инженерных систем

Бизнес-решения:

- Управление корпоративным контентом (ECM)
- Управление бизнес-процессами (BPM)
- Анализ данных (Data analytics)
- Заказная разработка
- Управление ресурсами предприятия (ERP)
- Автоматизация прикладных бизнес-процессов

Внедрение средств защиты информации:

- Сетевые средства защиты
- Средства защиты сервисов прикладного уровня
- Средства защиты от целевых кибератак

Инфокоммуникационные решения:

- Построение сетевой инфраструктуры
- Создание инфокоммуникационной среды

Решения промышленного Интернета вещей:

- Промышленный интернет вещей (IIoT)

[Источник](https://innostage-group.ru/services/engineering-systems/)

#### Программные продукты:

- Innostage IRP - решение собственной разработки класса IRP (Incident Response Platform), позволяющее автоматизировать мониторинг и реагирование на инциденты кибербезопасности и устранение уязвимостей ИБ. Решение может использоваться в качестве ядра для создания SOC, центров ГосСОПКА.

- Матрица доступа - это инструмент сотрудника информационной безопасности для отображения и контроля актуальных прав доступа к различным информационным источникам компании. 

- Система инвентаризации сетевых устройств Сканер - система инвентаризации сетевых устройств Сканер осуществляет сбор инвентаризационных данных по устройствам: рабочим станциям, серверам на ОС Windows и Linux, сетевому оборудованию и т.д.

- Цифровой штаб - программный комплекс для оперативного мониторинга и реагирования на разнородные угрозы безопасности предприятия. Система позволяет оперативно принимать управленческие решения на основе анализа больших массивов данных об инцидентах безопасности на объектах организации. 

- In-Dap Indicators - инструмент управления на основе индикаторов

- In-Dap Models - инструмент для моделирования

[Источник](https://innostage-group.ru/solutions/business/)

#### Используемые технологии, языки программирования:

- 1C

- SQL

- Linux

- Python

- NAT

- SOC

- TCP/IP

[Источник](https://innostage-group.ru/career/)

### 4. Основные клиенты компании:

- ПАО «Газпром»

- ПАО «НК «РОСНЕФТЬ»

- ПАО «Татнефть»

- АО «ТАИФ»

- ПАО «Интер РАО»

- ООО «СИБУР»

- АО «Росэнергоатом»

- ПАО «Нижнекамскнефтехим»

- ПАО «Россети Ленэнерго»

- АО «Газпромбанк»

- ПАО «МРСК Центра»

- АО «ЮниКредит Банк»

- ПАО «Транснефть»

- ПАО «Банк Уралсиб»

- ПАО «АК БАРС» БАНК

- Mriya Resort & SPA

- АО «Агентство по государственному заказу»

- АНО «Дирекция спортивных и социальных проектов»

- АО «Атомредметзолото»

- АО «Техснабэкспорт»

- Госкорпорация Росатом

[Источник](https://innostage-group.ru/clients/)

### 5. Основные веб-сайты компании и ее продуктов

[Основной веб-сайт](https://innostage-group.ru)

[Сайт AG TEAM](https://ag.team)

[Сайт cyberart](https://cyberart.ru)

### 6. Публичные сотрудники компании, активные участники ИТ и ИБ-сообщества, участники профильных конференций, Twitter, Mastodon, Телеграмм-каналов и т.д.

#### Ссылки на ресурсы

[ВКонтакте](https://vk.com/innostage)

[Telegram 1](https://t.me/innostage_group)

[Telegram 2](https://t.me/securiST)

[YouTube](https://www.youtube.com/channel/UCCTKU2evNISQ231BwRnqquA)

[Dzen](https://dzen.ru/innostage)

### 7. Основные достижения

Innostage стала лучшим партнером Check Point Software в России

[Источник](https://innostage-group.ru/press/news/gk-innostage-stala-luchshim-partnerom-check-point-software-v-rossii/)

## Вывод

Таким образом, с помощью методов OSINT была получена информация о компании Innostage 
